#!/usr/bin/env python3
"""
wiki-sessions-compose.py — render `memory/sessions/<uuid>.md` from
summarized turn data.

Reads:  /tmp/wiki-build/turns/<uuid>.summarized.jsonl
Writes: ~/.openclaw/workspace/memory/sessions/<uuid>.md (one per session)

Each per-session page format:

    # Session <uuid-short>

    **Started:** YYYY-MM-DD HH:MM TZ · **Ended:** YYYY-MM-DD HH:MM TZ
    **Turns:** N

    ## Turns

    ### YYYY-MM-DD

    - **HH:MM** — q: "first user prompt of the day, lightly trimmed"
      → a: One-line summary of assistant response.
    - **HH:MM** — q: "next prompt"
      → a: summary.

    ### YYYY-MM-DD (continuation)

    - **HH:MM** — q: "..." → a: summary.

The page is grouped by local date so cross-midnight sessions read as one
calendar list, not interleaved by UTC ordering.
"""
from __future__ import annotations

import json
import os
import re
import subprocess
import sys
from collections import defaultdict
from pathlib import Path

WORKSPACE = Path(os.environ.get("OPENCLAW_WORKSPACE", str(Path.home() / ".openclaw" / "workspace")))
TURNS_DIR = Path(os.environ.get("WIKI_BUILD_DIR", "/tmp/wiki-build")) / "turns"
SESSIONS_OUT_DIR = WORKSPACE / "memory" / "sessions"
SESSIONS_OUT_DIR.mkdir(parents=True, exist_ok=True)
RECONSTRUCT_SCRIPT = Path(__file__).parent / "wiki-session-reconstruct.py"

USER_TRUNCATE = 200  # chars in q line


def trim(s: str, n: int) -> str:
    s = s.strip().replace("\n", " ").replace("\r", " ")
    s = re.sub(r"\s+", " ", s)
    if len(s) > n:
        return s[: n - 1].rstrip() + "…"
    return s


def render_session(uuid: str, turns: list[dict]) -> str:
    if not turns:
        return ""
    short = uuid[:8]
    first_local = turns[0].get("ts_user_local", "")
    last_local = turns[-1].get("ts_user_local", "")

    # Group turns by local date prefix (YYYY-MM-DD)
    by_date: dict[str, list[dict]] = defaultdict(list)
    order: list[str] = []
    for t in turns:
        local = t.get("ts_user_local", "")
        date = local.split(" ", 1)[0] if local else "unknown"
        if date not in by_date:
            order.append(date)
        by_date[date].append(t)

    lines: list[str] = []
    lines.append(f"# Session `{short}`")
    lines.append("")
    lines.append(f"**UUID:** `{uuid}`  ")
    lines.append(f"**Started:** {first_local}  ")
    lines.append(f"**Ended:** {last_local}  ")
    lines.append(f"**Turns:** {len(turns)}")
    lines.append("")
    lines.append("## Turns")
    lines.append("")

    for i, date in enumerate(order):
        suffix = "" if i == 0 else " (continuation)"
        lines.append(f"### {date}{suffix}")
        lines.append("")
        for t in by_date[date]:
            local = t.get("ts_user_local", "")
            time_part = local.split(" ", 1)[1] if " " in local else ""
            time_short = time_part.rsplit(" ", 1)[0] if " " in time_part else time_part  # drop tz
            user = trim(t.get("user_text", ""), USER_TRUNCATE)
            summary = trim(t.get("summary", ""), 200)
            # Two-line per turn: bold timestamp on first line with the q,
            # then a continuation bullet line for the a (Markdown soft-break
            # via two trailing spaces keeps them visually grouped under one
            # bullet on most renderers, but this format renders cleanly
            # whether the renderer supports soft-breaks or not).
            lines.append(f"- **{time_short}**")
            lines.append(f"  - **q:** {user}")
            if summary:
                lines.append(f"  - **a:** {summary}")
            else:
                lines.append(f"  - **a:** _(no summary)_")
        lines.append("")

    lines.append("---")
    lines.append("")
    lines.append(f"📄 [Full transcript (prose mode)]({uuid}.full.md) · "
                 f"🔧 [With tool calls]({uuid}.tools.md)")
    lines.append("")
    lines.append("_Auto-generated by `scripts/wiki-sessions-compose.py`. Edit "
                 "summaries in `.summaries.json` to change wording across regens._")
    return "\n".join(lines).rstrip() + "\n"


def render_full(uuid: str, mode: str, out_name: str) -> bool:
    """Shell out to wiki-session-reconstruct.py to write <uuid>.<mode>.md.
    Returns True on success."""
    out_path = SESSIONS_OUT_DIR / out_name
    try:
        subprocess.run(
            [sys.executable, str(RECONSTRUCT_SCRIPT), uuid, "--mode", mode, "-o", str(out_path)],
            check=True,
            capture_output=True,
            text=True,
        )
        return True
    except subprocess.CalledProcessError as e:
        print(f"  ! {mode} render failed for {uuid}: {e.stderr.strip()[:200]}", file=sys.stderr)
        return False


def main():
    if not TURNS_DIR.exists():
        print(f"missing {TURNS_DIR}", flush=True)
        return

    written = 0
    full_written = 0
    tools_written = 0
    for f in sorted(TURNS_DIR.glob("*.summarized.jsonl")):
        uuid = f.stem.replace(".summarized", "")
        turns = []
        for line in f.read_text(encoding="utf-8").splitlines():
            if line.strip():
                turns.append(json.loads(line))
        if not turns:
            continue
        body = render_session(uuid, turns)
        out_path = SESSIONS_OUT_DIR / f"{uuid}.md"
        out_path.write_text(body, encoding="utf-8")
        written += 1

        # Generate companion full transcripts
        if render_full(uuid, "prose", f"{uuid}.full.md"):
            full_written += 1
        if render_full(uuid, "tools", f"{uuid}.tools.md"):
            tools_written += 1

        print(f"  wrote {out_path.name}  ({len(turns)} turns)")

    print(f"\nWrote {written} summary files, {full_written} prose transcripts, "
          f"{tools_written} tools transcripts to {SESSIONS_OUT_DIR}/")


if __name__ == "__main__":
    main()
