#!/usr/bin/env python3
"""
wiki-month-pages.py — generate per-month session index pages.

Reads:  /tmp/wiki-build/sessions-human.tsv   (produced by wiki-extract.sh)
Writes: ~/.openclaw/workspace/memory/sessions/YYYY-MM.md (one per month)

Each monthly page lists every session-date row that falls in that month,
with the same triple-link (`detail` / `full` / `tools`) as the index would
have shown inline. Sessions that span multiple months get a row in each
month's page (continuation rows are tagged).

Index.md will link to these pages instead of inlining the per-session list.
"""
from __future__ import annotations

import os
from collections import defaultdict
from datetime import datetime
from pathlib import Path

WORKSPACE = Path(os.environ.get("OPENCLAW_WORKSPACE", str(Path.home() / ".openclaw" / "workspace")))
OUT_DIR = Path(os.environ.get("WIKI_BUILD_DIR", "/tmp/wiki-build"))
SESSIONS_DIR = WORKSPACE / "memory" / "sessions"
SESSIONS_DIR.mkdir(parents=True, exist_ok=True)


def month_label(yyyymm: str) -> str:
    try:
        return datetime.strptime(yyyymm, "%Y-%m").strftime("%B %Y")
    except ValueError:
        return yyyymm


def month_key(date_str: str) -> str:
    return date_str[:7] if len(date_str) >= 7 else "????-??"


def discover_session_pages() -> tuple[set[str], set[str], set[str]]:
    """Return (has_detail, has_full, has_tools) sets of session UUIDs."""
    has_detail: set[str] = set()
    has_full: set[str] = set()
    has_tools: set[str] = set()
    if not SESSIONS_DIR.exists():
        return has_detail, has_full, has_tools
    for p in SESSIONS_DIR.glob("*.md"):
        name = p.name
        if name.endswith(".full.md"):
            has_full.add(name[: -len(".full.md")])
        elif name.endswith(".tools.md"):
            has_tools.add(name[: -len(".tools.md")])
        elif len(p.stem) == 36 and p.stem.count("-") == 4:
            # Skip monthly index pages (YYYY-MM.md) — they don't look like UUIDs
            has_detail.add(p.stem)
    return has_detail, has_full, has_tools


def read_human_tsv() -> list[tuple[str, str, str]]:
    """Return list of (date, uuid, msg) tuples."""
    path = OUT_DIR / "sessions-human.tsv"
    if not path.exists():
        return []
    rows: list[tuple[str, str, str]] = []
    for line in path.read_text(encoding="utf-8").splitlines():
        if not line.strip():
            continue
        cols = line.split("\t")
        if len(cols) < 4:
            continue
        date, uuid, _bytes, msg = cols[0], cols[1], cols[2], cols[3]
        msg = msg.strip()
        if len(msg) > 220:
            msg = msg[:217] + "..."
        rows.append((date, uuid, msg))
    return rows


def render_month(yyyymm: str, rows: list[tuple[str, str, str]],
                 has_detail: set[str], has_full: set[str], has_tools: set[str]) -> str:
    label = month_label(yyyymm)
    unique_uuids = {uuid for _d, uuid, _m in rows}
    lines = [
        f"# Sessions — {label}",
        "",
        f"**Date range:** {yyyymm}-01 — {yyyymm}-31  ",
        f"**Session-date rows:** {len(rows)}  ",
        f"**Unique sessions:** {len(unique_uuids)}",
        "",
        "[← Back to index](../index.md)",
        "",
        "---",
        "",
    ]
    # Sort newest first
    for date, uuid, msg in sorted(rows, key=lambda r: (r[0], r[1]), reverse=True):
        short = uuid[:8]
        link_parts = []
        if uuid in has_detail:
            link_parts.append(f"[detail]({uuid}.md)")
        if uuid in has_full:
            link_parts.append(f"[full]({uuid}.full.md)")
        if uuid in has_tools:
            link_parts.append(f"[tools]({uuid}.tools.md)")
        link_suffix = " — · " + " · ".join(link_parts) if link_parts else ""
        lines.append(f"- **{date} `{short}`** — {msg}{link_suffix}")
    lines.append("")
    lines.append("---")
    lines.append("")
    lines.append("_Auto-generated by `scripts/wiki-month-pages.py`._")
    return "\n".join(lines).rstrip() + "\n"


def main():
    rows = read_human_tsv()
    if not rows:
        print(f"No rows in {OUT_DIR}/sessions-human.tsv — run wiki-extract.sh first.")
        return

    has_detail, has_full, has_tools = discover_session_pages()

    # Group rows by YYYY-MM
    by_month: dict[str, list[tuple[str, str, str]]] = defaultdict(list)
    for row in rows:
        by_month[month_key(row[0])].append(row)

    written = 0
    for yyyymm in sorted(by_month.keys()):
        body = render_month(yyyymm, by_month[yyyymm], has_detail, has_full, has_tools)
        out_path = SESSIONS_DIR / f"{yyyymm}.md"
        out_path.write_text(body, encoding="utf-8")
        print(f"  wrote {out_path.name} ({len(by_month[yyyymm])} rows, "
              f"{len({u for _d, u, _m in by_month[yyyymm]})} unique sessions)")
        written += 1

    print(f"\nWrote {written} monthly session pages to {SESSIONS_DIR}/")


if __name__ == "__main__":
    main()
